

#using scraper_tweepy.py
import pandas as pd
from scraper_tweepy import scraper_tweepy
from connectDBNosql import connectDBinsert


df = pd.DataFrame()

FIAT=[["FIAT PANDA","FIAT 500","FIORINO","PUNTO","TALENTO","DUCATO",'POLSKI','LINEA','FIAT','FIAT HITACHI','FIAT KOBELCO','FIAT LANCIA','FIAT OM CARRELLI','TIPO'], '2021-03-01','FIAT']
PEUGEOT=[['AKVAL','PEUGEOT 206','PEUGEOT 508','PEUGEOT 208','PEUGEOT 108','PEUGEOT 2008','PEUGEOT 3008','PEUGEOT 108','PEUGEOT 5008','PEUGEOT 605'], '2021-03-01','PEUGEOT']
FORD=[['SIERRA','FIESTA','FOCUS','MONDEO','RANGER','MUSTANG','EXPLORER','BRONCO'],'2021-03-01','FORD']
RENAULT=[['SINPAR','CLIO','ARKANA','CAPTUR','KADJAR','MEGANE','TRAFIC','TWINGO'],'2021-03-01','RENAULT']
NISSAN=[['TITAN','JUKE','MICRA','NAVARA','LEAF','QASHQAI','CABSTAR','FIGARO'],'2021-03-01','NISSAN']
HONDA=[['ACCORD','CIVIC','JAZZ','CONCERTO'],'2021-03-01','HONDA']
OPEL=[['CROSSLAND','ASTRA','ADAMS','CORSA','GRANDLAND','MOKKA','ANTARA','CASCADA','CAMPO'],'2021-03-01','OPEL']
SUZUKI=[['SANTANA','MAGYAR','SWIFT','ACROSS','VITRA','BALENO'],'2021-03-01','SUZUKI']
VOLKSWAGEN=[['AMAROK','GOLF','CADDY','PASSAT','TIGUAN','TOUAREG','TRANSPORTER','JETTA','COCCINELLE'],'2021-03-01','VOLKSWAGEN']
SEAT=[['LEON','IBIZA','ARONA','ATECA','TOLEDO','EXEO','ALTEA'],'2021-03-01','SEAT']
KIA=[['CEED','PICANTO','NIRO','SORENTO','RIO','SPORTAGE','CERATO','OPTIMA','CARENS'],'2021-03-01','KIA']
HYUNDAI=[['I10','I20','I30'],'2021-03-01','HYUNDAI']
MERCEDES=[['CLA','CLASSE A','CLASSE B','CLASSE C','CLASSE E','CLASSE G','CLASSE GLA','ATEGO'],'2021-03-01','MERCEDES']
CITROEN=[['C1','C3','C4','BERLINGO','JUMPER','C5'],'2021-03-01','CITROEN']
BMW=[['SERIE 1','SERIE 2','SERIE 3','SERIE 4','SERIE 5','SERIE 6','SERIE 7','SERIE 8','X2','X3','X4','X5','X6','X7'],'2021-03-01','BMW']
AUDI=[['A1','A3','A4','A5','A6','A7','A8','Q2','Q3','Q4','Q5','Q6','Q7','Q8','TT','RS'],'2021-03-01','AUDI']
TOYOTA=[['AYGO','COROLLA','RAV','YARIS','AURIS','LAND CRUISER','TACOMA'],'2021-03-01','TOYOTA']
CHEVROLET=[['CAMARO','SILVERADO','AVEO','CRUZE','CAPTIVA','REZZO','SPARK','VOLT','BEAT'],'2021-03-01','CHEVROLET']

liste_all=[FIAT,PEUGEOT,FORD,RENAULT,NISSAN,HONDA,OPEL,SUZUKI,VOLKSWAGEN,SEAT,KIA,HYUNDAI,MERCEDES,CITROEN,BMW,AUDI,TOYOTA,CHEVROLET]


for i in range(len(liste_all)):
    print(i)
    df=scraper_tweepy(liste_all[i][0],df, liste_all[i][1],liste_all[i][2])
df.to_csv('tweets.csv',index=False)